/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rboxall' at '3/4/15 11:45 AM' with Gradle 2.3
 *
 * @author rboxall, @date 3/4/15 11:45 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
